name: super_glb
description: A dart glb manipulation software. Entirely developed by Copilot.
version: 1.0.4
repository: https://github.com/LiveUser/super_glb

environment:
  sdk: ^3.11.5

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  image: ^4.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
